ALTER TABLE theaters DROP COLUMN address;

ALTER TABLE theaters 
ADD COLUMN street VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN area VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN city VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN state VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN country VARCHAR(255) NOT NULL DEFAULT '';
